### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by ezos86** [oyyq99999/react-native-secure-storage#27]
Everytime I set a key, when I try to retrieve it, it shows undefined. Tried several times, many different ways. no luck.

![image](https://user-images.githubusercontent.com/1334598/76033864-255a6880-5ef2-11ea-8dae-8b0fe5830c69.png)

**Comment by KristineTrona** [comment]
@ezos86 can you share the code, where you are trying to set and retrieve the key?

**Comment by shlaing** [comment]
I faced that experience on Android only.

**Comment by ezos86** [comment]
I ended up moving to the keychain, and unfortunately, serialize and use email as key.
