### ISSUE TITLE
Repeated touch ID prompts when accessing storage

### ISSUE THREAD

**Issue by perry-mitchell** [oyyq99999/react-native-secure-storage#9]
I'm using your library in my project and it's fantastic! I've noticed a quirk however and I can't figure out why it's occurring. Whenever I write to the storage, touch authentication is _always_ requested. We use touch to unlock our app and then we write to storage, so we get 2 touch id requests one after the other.

We're using it in our password manager that has an iOS extension for password autofill, and you can see the configs [here](https://github.com/buttercup/buttercup-mobile/blob/95ce45c2a03cd532ece66bf50f914256885fd04b/source/shared/touchUnlock.js#L11) and [here](https://github.com/buttercup/buttercup-mobile/blob/95ce45c2a03cd532ece66bf50f914256885fd04b/source/compat/SecureStorageInterface.js#L6) (2 different uses of the storage).

We've tried seeing `accessControl` to `null` is in #6, but it still prompts us. The `authenticationPrompt` property seems to have no affect on what's displayed.

Have you seen this issue before? It's really bewildering us.

**Comment by perry-mitchell** [comment]
I guess what we're basically asking is this: Are we doing something wrong (which causes the endless prompts) or should we just stem the amount of writes we make (is it impossible to forgo the authentication prompts)?

If the device is unlocked (we're using `accessible: ACCESSIBLE.WHEN_UNLOCKED`), shouldn't it _just_ be available, without a prompt?

**Comment by perry-mitchell** [comment]
Nevermind, we were able to [fix the issue](https://github.com/buttercup/buttercup-mobile/pull/138). Thanks!

**Comment by oyyq99999** [comment]
I have looked at the pull request you mentioned but didn't get it. Seems the problem was caused by your own native code?

**Comment by perry-mitchell** [comment]
Yes it seems that it was it was this line:

```
(__bridge NSString *)kSecAttrAccessible: (__bridge id)accessible
```

Probably the value just wasn't getting passed.

**Comment by woodpav** [comment]
Is there a fix? The linked issue is from your own project not this one.

**Comment by perry-mitchell** [comment]
@woodpav See my previous comment. Adding that fixed it for us.

**Comment by fkrauthan** [comment]
@perry-mitchell Where exactly do I need to add that line you posted? Did you modify this plugins code or is that something you put into your own App codebase?

**Comment by woodpav** [comment]
I get an authentication prompt whenever I make a `SecureStorage.getItem` call. This could be the cause of this issue?

**Comment by perry-mitchell** [comment]
@fkrauthan One of our contributors submitted it, so I couldn't tell you sorry. Please feel free to [inspect where it was added](https://github.com/buttercup/buttercup-mobile/pull/138).
